FROM node:14.15.3-buster

ARG world_url
ENV WORLD_URL=${world_url}

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --pure-lockfile --network-timeout 600000

COPY ormconfig.json ./
COPY tsconfig.json ./
COPY tsconfig.server.json ./
COPY src/ ./src/
RUN yarn build:server

EXPOSE 3000

CMD ["node", "/app/dist/server/index.js"]
